name: 'Continuous Integration'

on: [pull_request, push]

permissions: read-all

jobs:
  ci-pipeline:
    name: 'Continuous Integration'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 2
          submodules: true
      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6
        with:
          distribution: temurin
          java-version: 17
      - name: 'Build cache'
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: 'Check'
        run: ./gradlew check -x integrationTest
      - name: 'Integration test'
        run: ./gradlew :pushiko-apns:integrationTest :pushiko-fcm:integrationTest
      - name: 'Check semantic versioning'
        id: semver
        if: github.event_name == 'pull_request'
        continue-on-error: true
        run: ./gradlew checkSemver --no-configuration-cache
      - name: 'Archive semver reports'
        if: github.event_name == 'pull_request' && steps.semver.outcome == 'failure'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: semver-reports
          path: '**/build/reports/japicmp/'
          if-no-files-found: ignore
      - name: 'Archive CycloneDX SBOMs'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: always()
        with:
          name: 'CycloneDX SBOMs'
          path: '**/build/reports/cyclonedx-direct/*-cyclonedx.json'
          if-no-files-found: ${{ job.status == 'success' && 'error' || 'ignore' }}
      - name: 'Generate repository CycloneDX SBOM'
        run: ./gradlew repositoryCyclonedxBom --no-configuration-cache
      - name: 'Archive repository SBOM'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: always()
        with:
          name: 'Repository SBOM'
          path: 'build/reports/cyclonedx/pushiko-*.cdx.json'
          if-no-files-found: ${{ job.status == 'success' && 'error' || 'ignore' }}
      - name: 'Tear down'
        if: always()
        run: |
          ./gradlew --stop

  fuzz:
    name: 'JVM Fuzzing'
    uses: ./.github/workflows/jvm-fuzzing.yml
    with:
      profile: smoke
