name: 'Periodic Integration Tests'

on:
  schedule:
    - cron: '0 22 * * SUN'

permissions: read-all

jobs:
  ci-pipeline:
    name: 'Continuous Integration'
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          submodules: true
      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6
        with:
          distribution: temurin
          java-version: 17
      - name: 'Integration tests'
        run: |
          ./gradlew integrationTest
